[package]
name = "flow_derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
# proc-macros
darling = "0.20.11"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"

# ui
gpui.workspace = true

[dev-dependencies]
flow.workspace = true
