[package]
name = "flow_derive"
version.workspace = true
edition.workspace = true

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = "2.0.87"

[lib]
proc-macro = true


[features]
default = []
gpui = []
