[package]
name = "headless"
version.workspace = true
edition.workspace = true

[dependencies]
simple_logger.workspace = true
eyre.workspace = true
log.workspace = true
radiant.workspace = true
spin_sleep = "1.3.2"
clap = { version = "4.5.40", features = ["derive"] }
