[package]
name = "headless"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
eyre.workspace = true
log.workspace = true
radlib.workspace = true
simple_logger.workspace = true
spin_sleep.workspace = true
