[package]
name = "rd-rigger"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
glam = "0.33.0"
serde.workspace = true
serde_path_to_error = "0.1.20"
quick-xml = { version = "0.39.2", features = ["serialize"] }
uuid = { version = "1.23.0", features = ["v4", "serde"] }
zip = { version = "8.5.1", default-features = false, features = ["deflate"] }
log.workspace = true
