[workspace]
members = ["app", "radiant", "dmx", "headless", "ui"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
clap = { version = "4.5.40", features = ["derive"] }
dmx = { path = "./dmx" }
derive_more = { version = "2.0.1", features = ["full"] }
eyre = "0.6.12"
gpui = { git = "https://github.com/zed-industries/zed", rev = "1e67e30" }
log = "0.4.27"
radiant = { path = "./radiant" }
serde = { version = "1.0.219", features = ["derive"] }
simple_logger = "5.0.0"
spin_sleep = "1.3.2"
thiserror = "2.0.12"
ui = { path = "./ui" }
