[workspace]
members = ["frames", "radiant", "ui"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
frames = { path = "frames" }
ui = { path = "ui" }

gpui = { git = "https://github.com/zed-industries/zed" }
