[workspace]
members = [
    "crates/radiant",
    # "crates/flow",
    "crates/ui",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
flow = { path = "crates/flow" }
ui = { path = "crates/ui" }

gpui = { git = "https://github.com/zed-industries/zed.git" }

anyhow = "1.0.89"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
slotmap = { version = "1.0.7", features = ["serde"] }
thiserror = "1.0.61"
log = "0.4.22"
env_logger = "0.11.5"
