[workspace]
members = ["flow", "flow2", "flow_gpui", "frames", "radiant", "ui"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
frames = { path = "frames" }
ui = { path = "ui" }
flow = { path = "flow" }
flow_gpui = { path = "flow_gpui" }

serde = "1"

gpui = { git = "https://github.com/zed-industries/zed" }
