[workspace]
members = ["core", "dmx", "headless"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
radiant = { path = "./core" }
dmx = { path = "./dmx" }

derive_more = { version = "2.0.1", features = [
    "add",
    "add_assign",
    "as_ref",
    "deref",
    "deref_mut",
    "display",
    "from",
    "from_str",
    "into",
    "mul_assign",
    "sum",
    "try_into",
] }
eyre = "0.6.12"
facet = "0.27.13"
facet-pretty = "0.23.20"
log = "0.4.27"
simple_logger = "5.0.0"
thiserror = "2.0.12"
