[workspace]
members = [
    "crates/radiant",
    "crates/ui",
    "crates/show",
    "crates/flow",
    "crates/dmx",
    "crates/geo",
    "crates/flow_derive",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
ui = { path = "crates/ui" }
flow = { path = "crates/flow" }
flow_derive = { path = "crates/flow_derive" }
show = { path = "crates/show" }
dmx = { path = "crates/dmx" }
geo = { path = "crates/geo" }

gpui = { git = "https://github.com/zed-industries/zed.git" }

anyhow = { version = "1.0.89", features = ["backtrace"] }
slotmap = { version = "1.0.7", features = ["serde"] }
thiserror = "1.0.61"
log = "0.4.22"
env_logger = "0.11.5"
strum = { version = "0.26.3", features = ["derive"] }
dirs = "5.0.1"

serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
