[workspace]
members = ["crates/radiant", "crates/ui", "crates/graph", "crates/show"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
ui = { path = "crates/ui" }
graph = { path = "crates/graph" }
show = { path = "crates/show" }

gpui = { git = "https://github.com/zed-industries/zed.git" }

anyhow = "1.0.89"
slotmap = { version = "1.0.7", features = ["serde"] }
thiserror = "1.0.61"
log = "0.4.22"
env_logger = "0.11.5"
