[workspace]
members = [
    "crates/dmx",
    "crates/flow",
    "crates/flow/flow_derive", "crates/flow2",
    "crates/radiant",
    "crates/sacn",
    "crates/ui",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.clippy]
needless_return = "allow"
single_match = "allow"
too_many_arguments = "allow"

[workspace.dependencies]
dmx = { path = "crates/dmx" }
flow = { path = "crates/flow" }
sacn = { path = "crates/sacn" }
ui = { path = "crates/ui" }

anyhow = "1.0"
dirs = "6.0.0"
gpui = { git = "https://github.com/zed-industries/zed", rev = "60ec55b1799d5d898921a230464ae361bfae85d9" }
log = "0.4.27"
thiserror = "2.0.12"
serde = "1"
