[workspace]
members = [
    "crates/dmx",
    "crates/flow",
    "crates/flow_derive",
    "crates/frames",
    "crates/radiant", "crates/sacn",
    "crates/ui",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.clippy]
needless_return = "allow"
single_match = "allow"

[workspace.dependencies]
# crates
dmx = { path = "crates/dmx" }
flow = { path = "crates/flow" }
flow_derive = { path = "crates/flow_derive" }
frames = { path = "crates/frames" }
ui = { path = "crates/ui" }
sacn = { path = "crates/sacn" }

# serialization
serde = "1"

# ui
gpui = { git = "https://github.com/zed-industries/zed" }

# error handling
eyre = "0.6.12"
thiserror = "2.0.12"

# logging
log = "0.4.27"
