[workspace]
members = ["flow", "frames", "radiant", "ui"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
# crates
frames = { path = "frames" }
ui = { path = "ui" }
flow = { path = "flow" }

# serialization
serde = "1"

# ui
gpui = { git = "https://github.com/zed-industries/zed" }

# error handling
eyre = "0.6.12"

# logging
log = "0.4.27"
