[workspace]
members = ["crates/radiant", "crates/ui", "crates/graph", "crates/show", "crates/flow_gpui", "crates/flow", "crates/dmx"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
ui = { path = "crates/ui" }
flow = { path = "crates/flow" }
flow_gpui = { path = "crates/flow_gpui" }
show = { path = "crates/show" }
dmx = { path = "crates/dmx" }

gpui = { git = "https://github.com/zed-industries/zed.git" }

anyhow = "1.0.89"
slotmap = { version = "1.0.7", features = ["serde"] }
thiserror = "1.0.61"
log = "0.4.22"
env_logger = "0.11.5"
strum = { version = "0.26.3", features = ["derive"] }
