[workspace]
members = ["dmx", "flow", "flow_derive", "frames", "radiant", "ui"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.lints.clippy]
needless_return = "allow"
single_match = "allow"

[workspace.dependencies]
# crates
frames = { path = "frames" }
ui = { path = "ui" }
flow = { path = "flow" }
flow_derive = { path = "flow_derive" }
dmx = { path = "dmx" }


# serialization
serde = "1"

# ui
gpui = { git = "https://github.com/zed-industries/zed" }

# error handling
eyre = "0.6.12"
thiserror = "2.0.12"

# logging
log = "0.4.27"
