
[package]
name = "rd-midi"
version.workspace = true
edition.workspace = true

[features]
serde = ["dep:serde"]

[dependencies]
flume.workspace = true
log.workspace = true
rd-service.workspace = true
thiserror.workspace = true

midir = "0.10.0"

# feature = "serde"
serde = { workspace = true, optional = true }

[dev-dependencies]
anyhow.workspace = true
pretty_env_logger.workspace = true
