[package]
name = "rd-midi"
version.workspace = true
edition.workspace = true

[dependencies]
facet.workspace = true
facet-error.workspace = true
flume.workspace = true
log.workspace = true
midir = "0.10.0"
rd-service.workspace = true

[dev-dependencies]
anyhow.workspace = true
pretty_env_logger.workspace = true
