[package]
name = "rd-engine"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
facet = { workspace = true, features = ["uuid", "nonzero"] }
facet-json.workspace = true
flume.workspace = true
log.workspace = true
midir = "0.10.0"
rd-service.workspace = true
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
pretty_env_logger.workspace = true
