[package]
name = "show"
version.workspace = true
edition.workspace = true

[dependencies]
flow.workspace = true
flow_gpui.workspace = true
gpui.workspace = true
ui.workspace = true
dmx.workspace = true

slotmap.workspace = true
anyhow.workspace = true
strum.workspace = true