[package]
name = "show"
version.workspace = true
edition.workspace = true

[dependencies]
dmx.workspace = true
flow = { workspace = true, features = ["derive", "gpui"] }

gpui.workspace = true
gdtf.workspace = true

anyhow.workspace = true
dirs.workspace = true
log.workspace = true

serde.workspace = true
serde_json.workspace = true
