[package]
name = "show"
version.workspace = true
edition.workspace = true

[dependencies]
flow = { workspace = true, features = ["gpui", "derive"] }
gpui.workspace = true
ui.workspace = true
dmx.workspace = true
geo.workspace = true

slotmap.workspace = true
anyhow.workspace = true
strum.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true

gdtf = "0.2.0"
itertools = "0.13.0"
