[package]
name = "rd"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
flume.workspace = true
log.workspace = true
rd-artnet = { workspace = true, features = ["serde"] }
rd-dmx = { workspace = true, features = ["serde"] }
rd-midi = { workspace = true, features = ["serde"] }
rd-rigger.workspace = true
rd-service.workspace = true
uuid = { workspace = true, features = ["v4", "serde"] }
serde.workspace = true
serde_json.workspace = true

rand = "0.10.2"

[dev-dependencies]
anyhow.workspace = true
pretty_env_logger.workspace = true
