[package]
name = "radiant"
version = "0.1.0"
edition = "2024"

[dependencies]
flow.workspace = true
frames.workspace = true
ui.workspace = true
serde.workspace = true
serde_json = "1"

gpui.workspace = true
