[package]
name = "rd-artnet"
version.workspace = true
edition.workspace = true

[dependencies]
bytes = "1.12.1"
facet = { workspace = true, features = ["net"] }
facet-error.workspace = true
facet-validate = "0.46.5"
flume.workspace = true
if-addrs = "0.15.0"
log.workspace = true
socket2 = { version = "0.6.4", features = ["all"] }

[dev-dependencies]
anyhow.workspace = true
pretty_env_logger.workspace = true
