[package]
name = "flow"
version.workspace = true
edition.workspace = true

[features]
serde = ["dep:serde"]
frontend_gpui = ["dep:gpui"]

[dependencies]
# feature = "serde"
serde = { workspace = true, optional = true }

# feature = "frontend_gpui"
gpui = { workspace = true, optional = true }
