[package]
name = "flow"
version.workspace = true
edition.workspace = true

[features]
serde = ["dep:serde"]

[dependencies]
# crates
ui.workspace = true

# ui
gpui.workspace = true

# feature = "serde"
serde = { workspace = true, optional = true }
