[package]
name = "radiant"
version.workspace = true
edition.workspace = true

[dependencies]
flow = { workspace = true, features = ["derive", "gpui"] }
ui.workspace = true
dmx.workspace = true
show.workspace = true

gpui.workspace = true

anyhow.workspace = true
log.workspace = true
env_logger.workspace = true
regex.workspace = true

clap = { version = "4.5.20", features = ["derive"] }

socket2 = { version = "0.5.7", features = ["all"] }
artnet_protocol = "0.4.3"
gdtf = "0.2.0"


rust-embed = "8.5.0"
rand = "0.8.5"
