[package]
name = "radiant"
version.workspace = true
edition.workspace = true

[dependencies]
ui.workspace = true
graph.workspace = true

gpui.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true

rust-embed = "8.5.0"
