[package]
name = "radiant"
version.workspace = true
edition.workspace = true

[dependencies]
show.workspace = true
ui.workspace = true
flow_gpui.workspace = true
dmx.workspace = true

gpui.workspace = true
anyhow.workspace = true
log.workspace = true
env_logger.workspace = true

rust-embed = "8.5.0"
socket2 = { version = "0.5.7", features = ["all"] }
artnet_protocol = "0.4.3"
