[package]
name = "radiant"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
# crates
dmx.workspace = true
frames.workspace = true
sacn.workspace = true
show.workspace = true
ui.workspace = true
flow.workspace = true

# serialization
serde.workspace = true

# ui
gpui.workspace = true

# error handling
anyhow.workspace = true

# logging
env_logger = "0.11.8"
log.workspace = true

clap = { version = "4.5.36", features = ["derive"] }
dirs.workspace = true
