[package]
name = "app"
version.workspace = true
edition.workspace = true

[dependencies]
clap.workspace = true
dmx.workspace = true
eyre.workspace = true
gpui.workspace = true
log.workspace = true
radiant.workspace = true
simple_logger.workspace = true
ui.workspace = true
