[package]
name = "graph"
version.workspace = true
edition.workspace = true

[dependencies]
gpui.workspace = true
ui.workspace = true

slotmap.workspace = true
thiserror.workspace = true

strum = { version = "0.26.3", features = ["derive"] }