[package]
name = "flow_derive"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
gpui.workspace = true

darling = "0.20.11"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"

[dev-dependencies]
flow.workspace = true
