[package]
name = "showfile"
version.workspace = true
edition.workspace = true

[dependencies]
flow = { workspace = true }
dmx.workspace = true

anyhow.workspace = true
log.workspace = true

serde.workspace = true
serde_json.workspace = true
